In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]


In [3]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size

voc_size = 10000


In [5]:
### One Hot Representation

one_hot_repre = [one_hot(words, voc_size) for words in sent]
one_hot_repre


[[6666, 8644, 1715, 7143],
 [6666, 8644, 1715, 3278],
 [6666, 3654, 1715, 9234],
 [3035, 6607, 6404, 7680, 5262],
 [3035, 6607, 6404, 7680, 272],
 [7398, 6666, 3197, 1715, 5993],
 [9765, 4718, 160, 7680]]

In [6]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding, InputLayer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [7]:
## Since the sentences are not of equal lenght, we set the max sentence lenght to add zeros to all the sentences for RNN
sent_lenght = 8
embedded_docks = pad_sequences(one_hot_repre,padding='pre', maxlen=sent_lenght)
embedded_docks


array([[   0,    0,    0,    0, 6666, 8644, 1715, 7143],
       [   0,    0,    0,    0, 6666, 8644, 1715, 3278],
       [   0,    0,    0,    0, 6666, 3654, 1715, 9234],
       [   0,    0,    0, 3035, 6607, 6404, 7680, 5262],
       [   0,    0,    0, 3035, 6607, 6404, 7680,  272],
       [   0,    0,    0, 7398, 6666, 3197, 1715, 5993],
       [   0,    0,    0,    0, 9765, 4718,  160, 7680]], dtype=int32)

In [8]:
### Feature representation
dim=10


In [9]:

model = Sequential()
model.add(InputLayer(input_shape=(sent_lenght,)))
model.add(Embedding(voc_size, dim, input_length=sent_lenght))
model.compile(optimizer='adam', loss='mse')




c:\Users\warlo\Desktop\DEEPLEARNING\deeplearning\Lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(
c:\Users\warlo\Desktop\DEEPLEARNING\deeplearning\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docks)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step


array([[[-0.00935277, -0.00211246, -0.03842207,  0.00125049,
          0.03849335, -0.03060987,  0.01620438,  0.03998431,
          0.02621103,  0.04771552],
        [-0.00935277, -0.00211246, -0.03842207,  0.00125049,
          0.03849335, -0.03060987,  0.01620438,  0.03998431,
          0.02621103,  0.04771552],
        [-0.00935277, -0.00211246, -0.03842207,  0.00125049,
          0.03849335, -0.03060987,  0.01620438,  0.03998431,
          0.02621103,  0.04771552],
        [-0.00935277, -0.00211246, -0.03842207,  0.00125049,
          0.03849335, -0.03060987,  0.01620438,  0.03998431,
          0.02621103,  0.04771552],
        [ 0.01924446, -0.00918106,  0.03889075,  0.03086561,
          0.03883832,  0.03169395, -0.02991207,  0.04574526,
          0.02609599, -0.03228496],
        [ 0.00412192, -0.01559984, -0.02432102, -0.04902984,
          0.01765298, -0.00223985, -0.03042431,  0.01787047,
         -0.00873929,  0.00482694],
        [-0.0303029 ,  0.00935832,  0.00735845, -0.0

In [13]:
embedded_docks[0]


array([   0,    0,    0,    0, 6666, 8644, 1715, 7143], dtype=int32)

In [16]:
model.predict(embedded_docks)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[[-0.00935277, -0.00211246, -0.03842207,  0.00125049,
          0.03849335, -0.03060987,  0.01620438,  0.03998431,
          0.02621103,  0.04771552],
        [-0.00935277, -0.00211246, -0.03842207,  0.00125049,
          0.03849335, -0.03060987,  0.01620438,  0.03998431,
          0.02621103,  0.04771552],
        [-0.00935277, -0.00211246, -0.03842207,  0.00125049,
          0.03849335, -0.03060987,  0.01620438,  0.03998431,
          0.02621103,  0.04771552],
        [-0.00935277, -0.00211246, -0.03842207,  0.00125049,
          0.03849335, -0.03060987,  0.01620438,  0.03998431,
          0.02621103,  0.04771552],
        [ 0.01924446, -0.00918106,  0.03889075,  0.03086561,
          0.03883832,  0.03169395, -0.02991207,  0.04574526,
          0.02609599, -0.03228496],
        [ 0.00412192, -0.01559984, -0.02432102, -0.04902984,
          0.01765298, -0.00223985, -0.03042431,  0.01787047,
         -0.00873929,  0.00482694],
        [-0.0303029 ,  0.00935832,  0.00735845, -0.0